spring.profiles.active=dev

spring.application.name=platzi-play

server.port=9080
server.servlet.context-path=/platzi-play/api

#LangChan4j
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini