spring.application.name=platzi-play

langchain4j.open-ai.chat-model.log-responses=true
langchain4j.open-ai.chat-model.log-requests=true

logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG

